# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Deploy to Firebase Hosting"
description: "A GitHub Action to deploy to Firebase Hosting"
author: "Jason Miller (https://github.com/developit) and Firebase"
branding:
  icon: "globe"
  color: "blue"
runs:
  using: "node12"
  main: "bin/action.min.js"
inputs:
  repoToken:
    description: "The GITHUB_TOKEN secret"
    required: false
  firebaseServiceAccount:
    description: "Firebase service account JSON"
    required: true
  expires:
    description: "How long should a preview live? See the preview channels docs for options"
    default: "7d"
    required: false
  projectId:
    description:
      "The project to deploy to. If you leave this blank, make sure you check in
      a .firebaserc file"
    required: false
  channelId:
    description: "The ID of the channel to deploy to. If you leave this blank,
      a preview channel and its ID will be auto-generated per branch or PR."
    required: false
  target:
    description:
      "The target name of the Hosting site to deploy to. If you leave this blank,
      the default target or all targets defined in the .firebaserc will be deployed to.
      Refer to the Hosting docs about [multiple sites](https://firebase.google.com/docs/hosting/multisites)
      for more information about deploy targets."
    required: false
  entryPoint:
    description:
      "The location of your firebase.json file, relative to the root of your
      directory"
    default: "."
    required: false
  message:
    description:
      "The deploy message. If provided with 'true', the head commit message will be used,
      otherwise the provided message will be used unless empty or 'false'."
    required: false
outputs:
  urls:
    description: The url(s) deployed to
  expire_time:
    description: The time the deployed preview urls expire
  details_url:
    description: A single URL that was deployed to
